### ISSUE TITLE
at24cxx_device_t at24cxx_init(const char *i2c_bus_name) 这个函数参数是一个，源码的这个函数是两个参数，文档不更新？

### ISSUE THREAD

**Issue by guangjieMVP** [XiaojieFan/at24cxx#11]
at24cxx_device_t at24cxx_init(const char *i2c_bus_name) 这个函数参数是一个，源码的这个函数是两个参数，文档不更新？

**Comment by guangjieMVP** [comment]
extern at24cxx_device_t at24cxx_init(const char *i2c_bus_name, uint8_t AddrInput);   .//AddrInput 参数是啥含义？

**Comment by XiaojieFan** [comment]
文档已经更新
