### ISSUE TITLE
实际测试发现AT24C02无法正常写入EEPROM

### ISSUE THREAD

**Issue by 14779771343** [XiaojieFan/at24cxx#13]
在测试发现AT24C02无法正常写入EEPROM，只能正确写入几个不连续的字节，查看代码发现在写入成功的时候没有延时如下所示
rt_err_t at24cxx_write(at24cxx_device_t dev, uint32_t WriteAddr, uint8_t *pBuffer, uint16_t NumToWrite)
{
    uint16_t i = 0;
    rt_err_t result;
    RT_ASSERT(dev);

    if(WriteAddr + NumToWrite > AT24CXX_MAX_MEM_ADDRESS)
    {
        return RT_ERROR;
    }

    result = rt_mutex_take(dev->lock, RT_WAITING_FOREVER);
    if (result == RT_EOK)
    {
        while (1) //NumToWrite--
        {
            if (at24cxx_write_one_byte(dev, WriteAddr, pBuffer[i]) != RT_EOK)
            {
                rt_thread_mdelay(EE_TWR);
            }
            else
            {
                WriteAddr++;
                i++;
            }
            if (i == NumToWrite)
            {
                break;
            }

        }
    }
    else
    {
        LOG_E("The at24cxx could not respond  at this time. Please try again");
    }
    rt_mutex_release(dev->lock);

    return RT_EOK;
}

将这个函数改成下面即可成功写入
rt_err_t at24cxx_write(at24cxx_device_t dev, uint32_t WriteAddr, uint8_t *pBuffer, uint16_t NumToWrite)
{
    uint16_t i = 0;
    rt_err_t result;
    RT_ASSERT(dev);

    if(WriteAddr + NumToWrite > AT24CXX_MAX_MEM_ADDRESS)
    {
        return RT_ERROR;
    }

    result = rt_mutex_take(dev->lock, RT_WAITING_FOREVER);
    if (result == RT_EOK)
    {
        while (1) //NumToWrite--
        {
            if (at24cxx_write_one_byte(dev, WriteAddr, pBuffer[i]) == RT_EOK)
            {
                WriteAddr++;
            }
            if (++i == NumToWrite)
            {
                break;
            }
            rt_thread_mdelay(EE_TWR);
        }
    }
    else
    {
        LOG_E("The at24cxx could not respond  at this time. Please try again");
    }
    rt_mutex_release(dev->lock);

    return RT_EOK;
}

**Comment by kylongmu** [comment]
> 在测试发现AT24C02无法正常写入EEPROM，只能正确写入几个不连续的字节，查看代码发现在写入成功的时候没有延时如下所示 rt_err_t at24cxx_write(at24cxx_device_t dev, uint32_t WriteAddr, uint8_t *pBuffer, uint16_t NumToWrite) { uint16_t i = 0; rt_err_t result; RT_ASSERT(dev);
> 
> ```
> if(WriteAddr + NumToWrite > AT24CXX_MAX_MEM_ADDRESS)
> {
>     return RT_ERROR;
> }
> 
> result = rt_mutex_take(dev->lock, RT_WAITING_FOREVER);
> if (result == RT_EOK)
> {
>     while (1) //NumToWrite--
>     {
>         if (at24cxx_write_one_byte(dev, WriteAddr, pBuffer[i]) != RT_EOK)
>         {
>             rt_thread_mdelay(EE_TWR);
>         }
>         else
>         {
>             WriteAddr++;
>             i++;
>         }
>         if (i == NumToWrite)
>         {
>             break;
>         }
> 
>     }
> }
> else
> {
>     LOG_E("The at24cxx could not respond  at this time. Please try again");
> }
> rt_mutex_release(dev->lock);
> 
> return RT_EOK;
> ```
> 
> }
> 
> 将这个函数改成下面即可成功写入 rt_err_t at24cxx_write(at24cxx_device_t dev, uint32_t WriteAddr, uint8_t *pBuffer, uint16_t NumToWrite) { uint16_t i = 0; rt_err_t result; RT_ASSERT(dev);
> 
> ```
> if(WriteAddr + NumToWrite > AT24CXX_MAX_MEM_ADDRESS)
> {
>     return RT_ERROR;
> }
> 
> result = rt_mutex_take(dev->lock, RT_WAITING_FOREVER);
> if (result == RT_EOK)
> {
>     while (1) //NumToWrite--
>     {
>         if (at24cxx_write_one_byte(dev, WriteAddr, pBuffer[i]) == RT_EOK)
>         {
>             WriteAddr++;
>         }
>         if (++i == NumToWrite)
>         {
>             break;
>         }
>         rt_thread_mdelay(EE_TWR);
>     }
> }
> else
> {
>     LOG_E("The at24cxx could not respond  at this time. Please try again");
> }
> rt_mutex_release(dev->lock);
> 
> return RT_EOK;
> ```
> 
> }

目前问题依旧，用at24cxx write 后读出只有第一个字节，改为你的每个都延迟后正常。

**Comment by XiaojieFan** [comment]
谢谢
